version: '3'

services:
  web:
    build: .
    command: sh -c "cd /usr/src/react/clint && npm start & cd /usr/src/react/server && npm start & tail -f /dev/null"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3000:3000"
